name: Checks

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
      - beta

jobs:
  lint:
    uses: ./.github/workflows/common.yml
    with:
      run_build: false
    steps:
      - name: Lint JS files
        run: yarn eslint