name: Lighthouse

on:
  push:
    branches:
      - master
      - beta

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: zendesk/checkout@v3
      - name: Setup Node.js
        uses: zendesk/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      # Disable AppArmor for Puppeteer compatibility
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Install node_modules
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Debug Secrets
        run: |
          echo "ZENDESK_EMAIL=${{ secrets.ZENDESK_EMAIL }}"
          echo "ZENDESK_API_TOKEN=${{ secrets.ZENDESK_API_TOKEN }}"
          echo "ZENDESK_SUBDOMAIN=${{ secrets.ZENDESK_SUBDOMAIN }}"
          echo "BRAND_ID=${{ secrets.BRAND_ID }}"
          echo "ZENDESK_THEME_ID=${{ secrets.ZENDESK_THEME_ID }}"
      - name: Upload theme
        run: node ./bin/theme-upload.js
        env:
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          BRAND_ID: ${{ secrets.BRAND_ID }}
      - name: Publish theme
        run: yarn zcli themes:publish --themeId=${{ secrets.ZENDESK_THEME_ID }}
        env:
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
      - name: Audit URLs using Lighthouse
        run: yarn test-a11y
        env:
          end_user_email: ${{ secrets.END_USER_EMAIL }}
          end_user_password: ${{ secrets.END_USER_PASSWORD }}
          subdomain: ${{ secrets.ZENDESK_SUBDOMAIN }}
          urls: |
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/categories/360002267479
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/sections/360003307259
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/articles/360010829359
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/requests/new