name: Release

on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    uses: ./.github/workflows/common.yml
    with:
      run_build: true
    steps:
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.release_bot_github_token }}
          GIT_AUTHOR_NAME: ${{ secrets.release_bot_git_name }}
          GIT_AUTHOR_EMAIL: ${{ secrets.release_bot_git_email }}
          GIT_COMMITTER_NAME: ${{ secrets.release_bot_git_name }}
          GIT_COMMITTER_EMAIL: ${{ secrets.release_bot_git_email }}